services:
  db:
    image: mysql:9.1.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: company
      MYSQL_USER: youruser
      MYSQL_PASSWORD: yourpassword
    volumes:
      - ./db/init/:/docker-entrypoint-initdb.d/
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - myapp-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: youruser
      DB_PASSWORD: yourpassword
      DB_NAME: company
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/employees || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - myapp-network

networks:
  myapp-network:
    driver: bridge
