services:
  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: company
      MYSQL_USER: youruser
      MYSQL_PASSWORD: yourpassword
    volumes:
      - ./db/init/:/docker-entrypoint-initdb.d/
    ports:
      - "3306:3306"
    networks:
      - myapp-network

networks:
  myapp-network:
    driver: bridge
