name: CI

# main ブランチに push または pull request があったときに実行
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. リポジトリのコードをチェックアウト
      - name: Check out repository
        uses: actions/checkout@v2

      # 2. Docker Compose をインストール
      - name: Install Docker Compose
        run: sudo apt-get install -y docker-compose

      # 3. Docker Compose でサービスを起動
      - name: Start services with Docker Compose
        run: docker-compose -f ./app/docker-compose.yml up -d

      # 4. Docker コンテナの状態を確認
      - name: List Docker containers
        run: docker ps -a

      # 5. test_db.sh を実行
      - name: Run test_db.sh
        run: bash ./test/test_db.sh

      # 6. test_backend.shを実行
      - name: Run backend tests
        run: bash ./test/test_backend.sh

      # 7. Docker Compose を終了
      - name: Stop services
        run: docker-compose -f ./app/docker-compose.yml down
